version: '3.6'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      # prevent mapping host node_modules to the container
      # see: https://stackoverflow.com/a/41035371
      - /src/node_modules
  mongo:
    env_file:
      - .env
    image: mongo:4.2-bionic
