version: '3.6'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/shorturls
      # prevent mapping host node_modules to the container
      # see: https://stackoverflow.com/a/41035371
      - /shorturls/node_modules
  mongo:
    env_file:
      - .env
    image: mongo:4.2-bionic
