version: '3.6'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/shorturls
  mongo:
    env_file:
      - .env
    image: mongo:4.2-bionic
